name: Multi-Version Simulation
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  simulation:
    strategy:
      matrix:
        tardis-version: ['release-2024.12.22', 'release-2024.12.15']
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Tardis
        uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis
          token: ${{ secrets.TARDIS_TOKEN }}
          ref: ${{ matrix.tardis-version }}
          path: tardis

      - name: Get atom data files
        uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis-regression-data
          token: ${{ secrets.TARDIS_TOKEN }}
          sparse-checkout: |
            atom_data/kurucz_cd23_chianti_H_He.h5
          sparse-checkout-cone-mode: false
          path: tardis-regression-data
          lfs: true
      
      - name: Copy atom data to Downloads
        run: |
          pwd
          mkdir -p Downloads/tardis-data
          cp tardis-regression-data/atom_data/kurucz_cd23_chianti_H_He.h5 Downloads/tardis-data/

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ./tardis/conda-linux-64.lock
          environment-name: tardis

      - name: Install tardis
        run: |
          pip install -e .
        working-directory: tardis
   
      # - name: Setup tmate session      
      #   uses: mxschmitt/action-tmate@v3
      - name: Generate Tests
        run: |
           pwd
           pytest tardis/spectrum/tests/test_spectrum_solver.py --tardis-regression-data=${{github.workspace}}/tardis-regression-data --generate-reference
        working-directory: tardis

      - uses: actions/upload-artifact@v4
        with:
            name: tardis-outputs-${{ matrix.tardis-version }}
            path: |
               tardis-regression-data/tardis/spectrum/tests/test_spectrum_solver/test_spectrum_solver/TestSpectrumSolver.h5
   
      - name: Show Generated Files
        if: always()
        run: |
          ls -R tardis-regression-data/tardis/spectrum/tests/test_spectrum_solver/test_spectrum_solver/

  download-artifacts:
    needs: simulation
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-artifacts

      - name: Set environment variables for paths
        run: |
          echo "ARTIFACT_PATHS=$(find downloaded-artifacts -type f | paste -sd ':' -)" >> $GITHUB_ENV
          echo "Paths set in environment variable ARTIFACT_PATHS:"
          echo $ARTIFACT_PATHS