name: Multi-Version Simulation
on:
  workflow_dispatch:

env:
  PYTEST_FLAGS: --tardis-regression-data= ${{github.workspace}}/tardis-regression-data --generate-reference
defaults:
  run:
    shell: bash -l {0}

jobs:
  simulation:
    strategy:
      matrix:
        tardis-version: ['release-2024.12.22', 'release-2024.12.15']
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Tardis
        uses: actions/checkout@v4
        with:
          repository: tardis-sn/tardis
          token: ${{ secrets.TARDIS_TOKEN }}
          ref: ${{ matrix.tardis-version }}

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-linux-64.lock
          environment-name: tardis

      - name: Install tardis
        run: |
          pip install -e .

      - name: G
        run: |
           mkdir -p tardis-regression-data

      - name: Setup tmate session      
        uses: mxschmitt/action-tmate@v3
   
      - name: Generate Tests
        run: |
           pytest ${{github.workspace}}/tardis/spectrum/tests/test_spectrum_solver.py ${{ env.PYTEST_FLAGS }}
        working-directory: tardis

      - uses: actions/upload-artifact@v4
        with:
            name: tardis-outputs-${{ matrix.tardis-version }}
            path: |
               tardis-regression-data/tardis/spectrum/tests/test_spectrum_solver/test_spectrum_solver/TestSpectrumSolver.h5
   
      - name: Show Generated Files
        if: always()
        run: |
          ls -R tardis-regression-data/tardis/spectrum/tests/test_spectrum_solver/test_spectrum_solver/