name: Simulation

on:
  workflow_dispatch: # manual trigger

defaults:
  run:
    shell: bash -l {0}

jobs:
    imulation:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
          - name: Clone kerzendorf group-data
            uses: actions/checkout@v4
            with:
                repository: KasukabeDefenceForce/tardis
                path: group-data
                token: ${{ secrets.TARDIS_TOKEN }}

          - name: Install TARDIS
            id: install-tardis
            run: |
                pip install git+https://github.com/tardis-sn/tardis.git@release-2024.12.22

          - name: Run Notebook
            run: jupyter nbconvert docs/quickstart.ipynb --to html --execute --ExecutePreprocessor.timeout=6000

          - name: Setup tmate session     
            uses: mxschmitt/action-tmate@v3
        #   - uses: actions/upload-artifact@v4
        #     with:
        #       name: changelog
        #       path: CHANGELOG.md
    