name: Simulation

on:
  workflow_dispatch: # manual trigger

defaults:
  run:
    shell: bash -l {0}

jobs:
    imulation:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              fetch-depth: 0
            
          - name: Clone Tardis
            uses: actions/checkout@v4
            with:
                repository: tardis-sn/tardis
                token: ${{ secrets.TARDIS_TOKEN }}
        
          - name: Generate Cache Key
            run: | 
             file_hash=$(cat conda-linux-64.lock | shasum -a 256 | cut -d' ' -f1)
             echo "file_hash=$file_hash" >> "${GITHUB_OUTPUT}"
            id: cache-environment-key
            shell: bash
        
          - uses: mamba-org/setup-micromamba@v1
            with:
                environment-file: conda-linux-64.lock
                cache-environment-key: ${{ steps.cache-environment-key.outputs.file_hash }}
                cache-downloads-key: ${{ steps.cache-environment-key.outputs.file_hash }}
                environment-name: tardis
                cache-environment: true
                cache-downloads: true
        
          - name: Install tardis
            run: |
                pip install -e .
                  
          - name: Run Notebook
            run: jupyter nbconvert docs/quickstart.ipynb --to html --execute --ExecutePreprocessor.timeout=6000

        #   - uses: actions/upload-artifact@v4
        #     with:
        #       name: 
        #       path:
    